FROM amazoncorretto:11-alpine
LABEL maintainer="sarwandria@gmail.com"

RUN apk --no-cache add bash curl unzip
RUN mkdir -p /app

COPY target/*.jar /app/app.jar
WORKDIR /app
ENTRYPOINT ["java","-jar","app.jar"]
